### ISSUE TITLE
Enhance the Navbar

### ISSUE THREAD

**Issue by amitxdewangan** [uti1man/dimencart#11]
Hey Harshit @uti1man ! 
I would like to **enhance the Navbar** by adding the **hover effect** on it. Please assign me this issue.

**Comment by binbard** [comment]
Thanks for checking in
Navbar has been updated in #2 
Checkout if it can be improved. Good luck

**Comment by theashu02** [comment]
I would like to contribute on this for Hacktoberfest 2022,
please assign me.

**Comment by amitxdewangan** [comment]
Hey @uti1man 
By mistake, I unassigned myself from this issue. Pls, assign me again.
Thanks!

**Comment by uti1man** [comment]
You go

**Comment by binbard** [comment]
You go !!
