### ISSUE TITLE
Adding navigation arrows to the cards in home section.

### ISSUE THREAD

**Issue by NateNear** [uti1man/dimencart#24]
Please allow me to add arrow for changing the cards in the "Home" section for enhanced user experience.

![issue 1 3](https://user-images.githubusercontent.com/92938055/193593200-80714806-3515-4c04-b2e5-c3f123de6d0e.PNG)

**Comment by binbard** [comment]
Great 👍🏼
Go for it [Consider starring ⭐ the repo]

**Comment by Hemang-05** [comment]
assign it to me, i will add arrows

**Comment by binbard** [comment]
Okay @Hemang-05, Go for it
[ Consider starring ⭐ the repo ]

**Comment by Hemang-05** [comment]
done
