### ISSUE TITLE
Add open graph image

### ISSUE THREAD

**Issue by Nakamcode** [uti1man/dimencart#3]
### An open graph is a preview image that shows when a link is shared on social media
_for more info about open graphs read the blog below_
https://ahrefs.com/blog/open-graph-meta-tags/

## Here's how it looks 
![captures_chrome-capture-2022-9-2 (5)](https://user-images.githubusercontent.com/89482825/193478144-2994e9e0-7de5-4f53-8f7c-68e324957bc8.png)

**Comment by binbard** [comment]
Perfect. You can now work on it
Good luck 👍🏼
