### ISSUE TITLE
Footer doesn't occupy max-width for mobile view

### ISSUE THREAD

**Issue by Samadeen** [uti1man/dimencart#30]
The items are clustered on the footer hence bad user experience.

**Comment by binbard** [comment]
Assigned. Go for it
[ consider starring ⭐ the repo ]

**Comment by Samadeen** [comment]
Okay.. I'm on it.

**Comment by Samadeen** [comment]
The first two pictures are what the footer originally looks like.
The second two pictures are what I've done. If you have any corrections to make kindly let me know

**Comment by binbard** [comment]
I think you forgot to add pictures?

**Comment by Samadeen** [comment]
![footer 1](https://user-images.githubusercontent.com/85469034/194652130-7ffb8cc4-9943-4aac-84f0-a0bc3aec47bd.png)
![footer 2](https://user-images.githubusercontent.com/85469034/194652134-ecda9bad-f0fc-4044-8f31-c2a4e1c863eb.png)
![Hacktoberfest Desktop footer 1](https://user-images.githubusercontent.com/85469034/194652138-35389aa7-f472-4f31-aada-48f39b54c7d3.png)
![Hacktoberfest Mobile Footer1](https://user-images.githubusercontent.com/85469034/194652139-6cc3b351-eeb4-4ad5-8e77-413d45fc7b1f.png)
Forgive me..

**Comment by Ayush-Kori** [comment]
Hey assign this to me.

**Comment by binbard** [comment]
@Samadeen I think what you're talking about has already been fixed in #2
It has also been reported in #33 
Checkout https://dimencart.surge.sh
You can repoen this issue if it is not what you're talking bout.
