### ISSUE TITLE
Services and About are not centered in the footer section

### ISSUE THREAD

**Issue by surya-doc** [uti1man/dimencart#33]
![image](https://user-images.githubusercontent.com/69008196/194102846-d7ed5022-3527-4d61-b789-4deb0ce1cc8b.png)
* The services and About sections are not centered and there is too much blank space in the footer section.
Want to work on this issue.

**Comment by binbard** [comment]
Can you share the exact dimensions of your screen

**Comment by Hemang-05** [comment]
i will place it in centre.

**Comment by binbard** [comment]
No. I asked you can you tell me the dimensions of the screen on which you are testing the site?
I checked all the dimensions and I dont think this issue is appearing

**Comment by surya-doc** [comment]
![image](https://user-images.githubusercontent.com/69008196/194385062-e93dcd3c-1a23-4274-9a10-77cbab6b999d.png)
* I mean the "Services" header text and the links under this ( Home, Explore, etc) are not aligned centrally. same as for the "About".

**Comment by uti1man** [comment]
I undertand that. I just want to know your screen dimensions (width x height).

I you're still confused and you have chrome browser install this:
https://chrome.google.com/webstore/detail/viewport-dimensions/kchdfagjljmhgapoonapmfngpadcjkhk
Then restart chrome, open any website.
Now activate the extension. Then you will see your screen dimensions at bottom-right corner
Send me screenshot of that. 
Hope you understood

**Comment by binbard** [comment]
I undertand that. I just want to know your screen dimensions (width x height).

Open this website: https://takumi0125.github.io/viewportChecker
And send me screenshot of that.
Hope you understood

**Comment by surya-doc** [comment]
![image](https://user-images.githubusercontent.com/69008196/194462133-cd5b26be-6414-4c36-a0d5-08def867898f.png)

**Comment by binbard** [comment]
Sorry bruh, I think you have visited https://dimencart.surge.sh (it was not updated)
This was fixed in pr #2
Thankyou btw. I have updated that here too https://dimencart.surge.sh
