### ISSUE TITLE
add CONTRIBUTION.md

### ISSUE THREAD

**Issue by sachin-404** [uti1man/dimencart#6]

**Comment by sachin-404** [comment]
adding a contribution.md will help a lot of folks who are new to the open source contribution. Please assign this to me.

**Comment by johnwinifred** [comment]
hello, please I would love to work on this issue

**Comment by uti1man** [comment]
@johnwinifred Okay go for it.
Good luck 👍

**Comment by binbard** [comment]
@johnwinifred Okay go for it.
Also star ⭐ the repo (believe me its free)
Good luck 👍
