### ISSUE TITLE
Adding a Favicon to the website

### ISSUE THREAD

**Issue by KanishkDadhich** [uti1man/dimencart#8]
Hey :)
I can see that this website doesn't have any kind of favicon. it would be quite captivating if this had one.
And I would like to work on this issue under Hacktoberfest.
Thanks :)

**Comment by Kshiti-24** [comment]
hey please assign me this issue i want to add a favicon to your website

**Comment by binbard** [comment]
Assigned. Whoever first & minimal would be considered
Good luck to both 👍🏼

**Comment by johnwinifred** [comment]
Please assign this issue to me

**Comment by uti1man** [comment]
Resolved in #22

**Comment by binbard** [comment]
Resolved in #22
