### ISSUE TITLE
[FEATURE] Improving Slider User Experience

### ISSUE THREAD

**Issue by at-the-vr** [uti1man/dimencart#9]
Hi Harshit, Atharva this side and I was wondering if you wanna upgrade your Slider User Experience.
I am providing a link showcasing just few changes I did with slider navigation [fork-dimencart-itsEobard2025](https://itseobard2025.github.io/dimencart/)
I can't say why the Images are not rendered here but the highlight is only on the Slider as i said.

Changes :
- the bullets are clickable
- the animation are not disabled upon interaction

**Comment by binbard** [comment]
Thanks for checking in
Yeah this was needed.
Assigned, Good luck 👍🏼

**Comment by binbard** [comment]
Resolved in #34
